baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gabriela Reynoso - Portfolio'
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Pagination settings:

# For Hugo versions 0.128.0 and above, use the following settings:
# This will set the number of items per page for newer versions.
[pagination]
  pagerSize = 5

# For Hugo versions below 0.128.0, uncomment the line below and comment out the [pagination] block above:
#paginate = 5 # Sets the number of items per page for older versions.


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Creative Portfolio Theme for Hugo"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Work"
    url = "/works/"
    weight = 3

  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Pages"
    weight = 5
    hasChildren = true

  
  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Gabriela Reynoso"
    author__bio = "Senior Software Engineer. "
    author__avatar = "/images/mypicture.jpg"

  # Social Links
  [[params.social]]
    icon = "ion-logo-linkedin"
    name = "Linkedin"
    link = "https://www.linkedin.com/in/gabriela-reynoso-082a614b/"

  

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Gabriela Reynoso"
    hero__description = "Hi, I'm Gabriela Reynoso a Senior Software Engineer"
    hero__image = "/images/frontpage.png"


    #-------------------------------
    # Logos Settings
    [params.logos]
      enable = true
      logos__title = "I’ve worked with some great сompanies"

    [[params.logo_item]]
      name = "Banco GyT Continental"
      link = "https://www.gtc.com.gt/"
      image = "/images/gyt-logo.png"

    [[params.logo_item]]
      name = "dXLatam"
      link = "https://www.dxlatam.com/"
      image = "/images/logo-dxlatam.png"

    [[params.logo_item]]
      name = "Allied Global Technollogy Services"
      link = "https://alliedglobal.com/"
      image = "/images/Allied-Global-logo.png"



  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = false
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address..."
    mailchimp__button__text = "Subscribe" # Add your button text

#-------------------------------
  # Show hero image
  [params.hero_showimage]
    enable = true
    

  #-------------------------------
  # Work Settings
  [params.work]
    enable = true
    work__title= "Work"
    work__description= "Here are my highlighted projects"


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = false
    testimonial__title = "Clients"
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Hanna Septimus"
    image = "https://via.placeholder.com/400x400"
    designation = "Product Designer"
    link = "https://twitter.com/"
    content = "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  
  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Articles"
    blog__description = ""


  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__background__image = "https://via.placeholder.com/1920x1080"


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "gabriela.reynoso@gmail.com" # Add your form_id

    # NOTE
    # Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = false
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
